
#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: Your Email ID Username
#    password: YourEmail ID Password
#
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          ssl:
#            trust: smtp.gmail.com # Add this line
#      debug: true